### ISSUE TITLE
نیاز به تکمیل لیست آی‌پی‌ها

### ISSUE THREAD

**Issue by vfarid** [vfarid/cf-clean-ips#1]
اینجا میخوایم یه لیست از آی‌پی‌های تمیز اپراتورهای مختلف با همکاری جمعی ایجاد کنیم.
هر کس میتونه مشارکت کنه، اسم اپراتورهایی که روی اونها امکان تست داره رو تو کامنت بنویسه، درنهایت با توجه به داوطلبین، نحوه‌ی اجرای کار رو تشریح می‌کنم.

**Comment by pedram795** [comment]
شاتل، مخابرات

**Comment by hasanejraei** [comment]
همراه اول، صبانت.

**Comment by Dexter050** [comment]
همراه اول ، ایرانسل ، رایتل

**Comment by hamedddg** [comment]
ایرانسل همراه اول

**Comment by aprilboy9** [comment]
شاتل موبایل و ایرانسل

**Comment by LonUp** [comment]
مخابرات
همراه اول
ایرانسل

**Comment by mahdiyarv2ray** [comment]
پارس آنلاین ٫ همراه اول

**Comment by GrtGoals** [comment]
شاتل،همراه اول،ایرانسل

**Comment by smahdiyar** [comment]
پارس آنلاین ٫ همراه اول

**Comment by Amirkhaksar** [comment]
Shatel , Respina , Mokhaberat 
HamrahAval, Irancell , Rightel

**Comment by shahryarjb** [comment]
های وب - ایرانسل ثابت - ایرانسل همراه

**Comment by aliwebto** [comment]
شاتل موبایل - ایرانسل - همراه اول - مخابرات - شاتل - آسیاتک

**Comment by vahidiano** [comment]
سامان تل

**Comment by terminator1362** [comment]
ایرانسل 😢

**Comment by joiniran** [comment]
شاتل ای دی اس ال

**Comment by jakvilson13** [comment]
همراه اول و ایرانسل

**Comment by AliShFar** [comment]
مخابرات تهران (ADSL)

**Comment by Salymokh** [comment]
رایتل

**Comment by scriptax** [comment]
ایرانسل، رایتل، مخابرات

**Comment by pooya30** [comment]
همراه اول

**Comment by vaaaab** [comment]
رایتل 
همراه اول
ایرانسل
مخابرات

**Comment by ali8mib** [comment]
آسیاتک مخابرات

**Comment by Sysop0098** [comment]
ایرانسل،  همراه اول

**Comment by blackvoidx** [comment]
ایرانسل و آسیاتک

**Comment by Angebini** [comment]
سلام
ایرانسل ، مخابرات ، رسپینا

**Comment by black-birdB52** [comment]
ثابت ایرانسل - همراه اول - ایرانسل(همراه)

**Comment by bamdad23** [comment]
صفرویک
شاتل
مخابرات
های وب
صبانت
آسیاتک
پارس آنلاین
فن آوا
پیشگامان
رهام داتک
دیده بان نت
حلما گستر

**Comment by CIAHAT** [comment]
پیشگامان، همراه اول

**Comment by vmmehr** [comment]
شاتل همراه اول

**Comment by bamdad23** [comment]
اینجا لیست کامل آی پی ها شون به همراه تفکیک استانیشون رو هم میتونید پیدا کنید [https://www.nirsoft.net/countryip/ir.html](url)

**Comment by bamdad23** [comment]
> اینجا لیست کامل آی پی ها شون به همراه تفکیک استانیشون رو هم میتونید پیدا کنید [https://www.nirsoft.net/countryip/ir.html](url)

اسم اوپراتورها هم به همراه آی پی ها هست. چه ثابت و چه همراه. بعضی ها رو من اسمشون رو تا الان هم نشنیده بودم حتی

**Comment by bamdad23** [comment]
[https://www.nirsoft.net/countryip/ir.csv](url)
اینم لینک دنلود تفکیک شده با کاما

**Comment by xlirezx** [comment]
همراه اول
پارس آنلاین
ایرانسل

**Comment by mcseali** [comment]
شاتل موبایل
ایرانسل ثابت

**Comment by salarebi** [comment]
رایتل

**Comment by heyatzadeh** [comment]
پیشگامان ایرانسل

**Comment by ErfanTech** [comment]
شاتلadsl،شاتل‌موبایل،ایرانسل،همراه‌اول

**Comment by Mehdiv97** [comment]
مبین نت

**Comment by armingh77** [comment]
مبین‌نت

**Comment by SinaFXD** [comment]
ایرانسل ، همراه اول ، مبین نت

**Comment by nazanin1086** [comment]
ایرانسل

**Comment by vfarid** [comment]
@bamdad23 این لیست که شما فرستادی، رنج آی‌پی‌های اپراتورها هستش. ما دنبال آی‌پی‌های آزاد کلادفلر روی اپراتورها هستیم.

**Comment by bamdad23** [comment]
> @bamdad23 این لیست که شما فرستادی، رنج آی‌پی‌های اپراتورها هستش. ما دنبال آی‌پی‌های آزاد کلادفلر روی اپراتورها هستیم
میدونم بزرگوار، اما شما در اینجا لیست اوپراتورهای ایرانی را خواسته بودید، بنده لیستشون که شامل نام و رنج آی پیهاشون هست رو خدمتتون دادم. طبق این لیست ما مثلا ایرانسل تبریز شاید همان فیلترینگ تهران را نداشته باشد. اگر بکارتان میای که خوشحالم اگر هم نه که میتوانید نادیده بگیریدش.
من خارج از ایرانم و دوست دارم بتونم کمکی بهتون بکنم. دمتون گرم که زحمت میکشیدید برای دسترسی مردم بهنت بدون سانسور. خسته نباشید

**Comment by vfarid** [comment]
> > @bamdad23 این لیست که شما فرستادی، رنج آی‌پی‌های اپراتورها هستش. ما دنبال آی‌پی‌های آزاد کلادفلر روی اپراتورها هستیم
> > میدونم بزرگوار، اما شما در اینجا لیست اوپراتورهای ایرانی را خواسته بودید، بنده لیستشون که شامل نام و رنج آی پیهاشون هست رو خدمتتون دادم. طبق این لیست ما مثلا ایرانسل تبریز شاید همان فیلترینگ تهران را نداشته باشد. اگر بکارتان میای که خوشحالم اگر هم نه که میتوانید نادیده بگیریدش.
> > من خارج از ایرانم و دوست دارم بتونم کمکی بهتون بکنم. دمتون گرم که زحمت میکشیدید برای دسترسی مردم بهنت بدون سانسور. خسته نباشید

متشکرم

**Comment by SaeedRZ70** [comment]
فن اوا

**Comment by Aitesla** [comment]
شاتل، همراه اول

**Comment by vfarid** [comment]
> Shatel , Respina , Mokhaberat 
> HamrahAval, Irancell , Rightel

من اسکریپت اسکن رو اصلاح کنم و بهش قابلیت اسکن بر اساس لیست بدم، میتونید آی‌پی‌های دریافتی روی این پراتورها رو وریفای کنید و مرج کنید به main؟

**Comment by ali9sr** [comment]
مخابرات
ایرانسل

**Comment by bamdad23** [comment]
> > Shatel , Respina , Mokhaberat
> > HamrahAval, Irancell , Rightel
> 
> من اسکریپت اسکن رو اصلاح کنم و بهش قابلیت اسکن بر اساس لیست بدم، میتونید آی‌پی‌های دریافتی روی این پراتورها رو وریفای کنید و مرج کنید به main؟

بمن بگید چکار کنم در خدمتتم. اگر از دست من کاری ساخته است

**Comment by mehr1581** [comment]
رایتل

**Comment by MoAli23** [comment]
همراه اول
مخابرات

**Comment by ghermez** [comment]
برای اسکن زیتل میتونم
برای چک آی پی ها: زیتل، tdlte ایرانسل، رایتل، همراه اول

**Comment by Shjpr9** [comment]
ایرانسل، مخابرات، همراه اول، شاتل

**Comment by Dementora** [comment]
مبین نت
 من یه پیشنهاد داشتم الان دوستان زیادی از جا های مختلف اعلام آمادگی کردن برای اسکن و هی آدمای مختلفی میان و میرن
بیاین اینطوری مدریت کنید که یسری تنظیمات سرعت و پینگ مینیمم هم اعلام کنین برای تنظیمات اسکنر بعد دو حالت بزارین یه عده برن رنج کلی ایپی های کلادفلر رو اسکن کنن و بفرستن (یا تو اسکنر اپشن باشه خودش اوتومات بفرسته) و اون ایپی های کلی توی صفحه اوپراتور مربوطه نمایش داده بشه بعد یه عده دیگه از داوطلب ها بیان اون ایپی های اسکن شده رو دوباره تست کنن (با اسکنر های دیگه یا حتی روی کانفیگشون ست کنن تست دانلود بگیرن بعد هرکس این ایپی های برگزیده خودش رو هم دوباره بفرسته اون وقت اسکریپت بیاد ببینه هر ایپی که بیشترین تکرار رو داشته رو به عنوان برگزیده به بقیه نشون بده که روی دامنه شون a رکورد بزنن بهش دائماً ایپی ها بروز میمونه و همه مشارکت دارن به میزانی که میخوان وقت بزارن

**Comment by MoeinNS** [comment]
شاتل ، همراه اول، ایرانسل، رایتل

**Comment by bamdad23** [comment]
میتونید یک اسکریپت بنویسید که آی پی اوپراتورهای ایران رو اسپوف کنه و ما بتونیم از خارج براتون اسکن کنیم و دنبال آی پی تمیز بگردیم؟ چون هم پهنای باند بهتری داریم هم از نظر سخت افزاری وضعیتمون احتمالا بهتره.

**Comment by vfarid** [comment]
> > > Shatel , Respina , Mokhaberat
> > > HamrahAval, Irancell , Rightel
> > 
> > من اسکریپت اسکن رو اصلاح کنم و بهش قابلیت اسکن بر اساس لیست بدم، میتونید آی‌پی‌های دریافتی روی این پراتورها رو وریفای کنید و مرج کنید به main؟
> 
> بمن بگید چکار کنم در خدمتتم. اگر از دست من کاری ساخته است

متشکرم، نه کسی باید باشه که به اپراتورهای مربوطه تو ایران دسترسی داشته باشه.

**Comment by NyctoMan** [comment]
ایرانسل ، همراه اول ، شاتل موبایل ، سامانتل ، مخابرات

**Comment by vfarid** [comment]
> مبین نت
>  من یه پیشنهاد داشتم الان دوستان زیادی از جا های مختلف اعلام آمادگی کردن برای اسکن و هی آدمای مختلفی میان و میرن
> بیاین اینطوری مدریت کنید که یسری تنظیمات سرعت و پینگ مینیمم هم اعلام کنین برای تنظیمات اسکنر بعد دو حالت بزارین یه عده برن رنج کلی ایپی های کلادفلر رو اسکن کنن و بفرستن (یا تو اسکنر اپشن باشه خودش اوتومات بفرسته) و اون ایپی های کلی توی صفحه اوپراتور مربوطه نمایش داده بشه بعد یه عده دیگه از داوطلب ها بیان اون ایپی های اسکن شده رو دوباره تست کنن (با اسکنر های دیگه یا حتی روی کانفیگشون ست کنن تست دانلود بگیرن بعد هرکس این ایپی های برگزیده خودش رو هم دوباره بفرسته اون وقت اسکریپت بیاد ببینه هر ایپی که بیشترین تکرار رو داشته رو به عنوان برگزیده به بقیه نشون بده که روی دامنه شون a رکورد بزنن بهش دائماً ایپی ها بروز میمونه و همه مشارکت دارن به میزانی که میخوان وقت بزارن

همین کار رو میخوام بکنم. از بین کسانی که بیشترین دسترسی بهداپراتورها رو دارن نفراتی رو باید پیدا کنم که آی‌پی‌ها رو وریفای کنن، باقی هم اسکن و pull request

**Comment by vfarid** [comment]
> مبین نت
>  من یه پیشنهاد داشتم الان دوستان زیادی از جا های مختلف اعلام آمادگی کردن برای اسکن و هی آدمای مختلفی میان و میرن
> بیاین اینطوری مدریت کنید که یسری تنظیمات سرعت و پینگ مینیمم هم اعلام کنین برای تنظیمات اسکنر بعد دو حالت بزارین یه عده برن رنج کلی ایپی های کلادفلر رو اسکن کنن و بفرستن (یا تو اسکنر اپشن باشه خودش اوتومات بفرسته) و اون ایپی های کلی توی صفحه اوپراتور مربوطه نمایش داده بشه بعد یه عده دیگه از داوطلب ها بیان اون ایپی های اسکن شده رو دوباره تست کنن (با اسکنر های دیگه یا حتی روی کانفیگشون ست کنن تست دانلود بگیرن بعد هرکس این ایپی های برگزیده خودش رو هم دوباره بفرسته اون وقت اسکریپت بیاد ببینه هر ایپی که بیشترین تکرار رو داشته رو به عنوان برگزیده به بقیه نشون بده که روی دامنه شون a رکورد بزنن بهش دائماً ایپی ها بروز میمونه و همه مشارکت دارن به میزانی که میخوان وقت بزارن

همین کار رو میخوام بکنم. از بین کسانی که بیشترین دسترسی به اپراتورها رو دارن نفراتی رو باید پیدا کنم که آی‌پی‌ها رو وریفای کنن، باقی هم اسکن و pull request

**Comment by vfarid** [comment]
> میتونید یک اسکریپت بنویسید که آی پی اوپراتورهای ایران رو اسپوف کنه و ما بتونیم از خارج براتون اسکن کنیم و دنبال آی پی تمیز بگردیم؟ چون هم پهنای باند بهتری داریم هم از نظر سخت افزاری وضعیتمون احتمالا بهتره. 

نمیشه، باید سیستم متصل به همون اپراتور باشه.

**Comment by vfarid** [comment]
> میتونید یک اسکریپت بنویسید که آی پی اوپراتورهای ایران رو اسپوف کنه و ما بتونیم از خارج براتون اسکن کنیم و دنبال آی پی تمیز بگردیم؟ چون هم پهنای باند بهتری داریم هم از نظر سخت افزاری وضعیتمون احتمالا بهتره. 

نمیشه، باید سیستم متصل به همون اپراتور باشه.

**Comment by Yelesee** [comment]
ایرانسل
همراه اول
مخابرات
مبین نت

**Comment by kazem** [comment]
مبین‌نت، زی‌تل، های‌وب

**Comment by emdarx** [comment]
ایرانسل، همراه اول، شاتل، مخابرات

**Comment by proxystore11** [comment]
مخابرات،ایرانسل

**Comment by saeex71** [comment]
مبین نت
ایرانسل ثابت - همراه
رایتل
همراه اول
مخابرات vdsl

**Comment by ahooee** [comment]
ایرانسل
شاتل 
همراه اول 
رایتل

**Comment by Navidmirzaei** [comment]
همراه اول
ایرانسل
شاتل
فناپ
پتیاک

**Comment by newwebb** [comment]
mobin
avl

**Comment by mehran66666** [comment]
hamrah, mokhaberat

**Comment by Amirkhaksar** [comment]
> > مبین نت
> > من یه پیشنهاد داشتم الان دوستان زیادی از جا های مختلف اعلام آمادگی کردن برای اسکن و هی آدمای مختلفی میان و میرن
> > بیاین اینطوری مدریت کنید که یسری تنظیمات سرعت و پینگ مینیمم هم اعلام کنین برای تنظیمات اسکنر بعد دو حالت بزارین یه عده برن رنج کلی ایپی های کلادفلر رو اسکن کنن و بفرستن (یا تو اسکنر اپشن باشه خودش اوتومات بفرسته) و اون ایپی های کلی توی صفحه اوپراتور مربوطه نمایش داده بشه بعد یه عده دیگه از داوطلب ها بیان اون ایپی های اسکن شده رو دوباره تست کنن (با اسکنر های دیگه یا حتی روی کانفیگشون ست کنن تست دانلود بگیرن بعد هرکس این ایپی های برگزیده خودش رو هم دوباره بفرسته اون وقت اسکریپت بیاد ببینه هر ایپی که بیشترین تکرار رو داشته رو به عنوان برگزیده به بقیه نشون بده که روی دامنه شون a رکورد بزنن بهش دائماً ایپی ها بروز میمونه و همه مشارکت دارن به میزانی که میخوان وقت بزارن
> 
> همین کار رو میخوام بکنم. از بین کسانی که بیشترین دسترسی بهداپراتورها رو دارن نفراتی رو باید پیدا کنم که آی‌پی‌ها رو وریفای کنن، باقی هم اسکن و pull request

به نظرم برای کسایی که میخوان وریفای کنن اگر بشه مثلا یه وب سرور بیاد بالا این لیست رو از گیتهاب به طریقی بخونه و اون افراد آی پی ها رو وریفای کنن و  خود اون وب سرور بیاد لیست آی پی های تمیز ور فای شده رو بفرسته رو گیت هاب

**Comment by ahmadire** [comment]
پیشگامان و همراه اول

**Comment by eskan27** [comment]
مخابرات همراه اول

**Comment by Redshado0w** [comment]
سلام و احترام
trojan , vmess , vless 
ws , grpc , tcp
رو سرور آماده برای تست دارم 
آسیاتک
مخابرات
همراه اول
ایرانسل
شاتل موبایل
آپتل
 رو امکان تست دارم

**Comment by HammaH24** [comment]
Mobinnet

**Comment by amirmhr1993** [comment]
همراه اول
های وب

**Comment by kamal-dev1** [comment]
ایرانسل
همراه اول
رایان کده آپادانا
شاتل

**Comment by vfarid** [comment]
دوستان خیلی ممنونم از ابراز آمادگی و همکاری همگی شما.
هر جوری حساب کردم دیدم واقعا فرصت نمیکنم این حجم کار رو جمع کنم و به این شکل انجامش ندم بهتره.
اگه هر کدومتون بتونه یه همچین کار گروهی رو انجام بده و این لیست رو آماده کنه خیلی کار مثبتیه و من حتما معرفی میکنم و توی کدها ازش استفاده می کنم.

بازم ممنونم از همگی شما

**Comment by logicianmik** [comment]
وینکس
سامانتل
شاتل موبایل
