### ISSUE TITLE
درخواست مشارکت

### ISSUE THREAD

**Issue by HamedSanaei** [vfarid/cf-clean-ips#10]
سلام مهندس جان. من سعی میکنم هر صبح بروز کنم. هر سابدامین ۵ آیپی.
ایرانسل:
mtnh.hamedgeek.top   

همراه اول:
mcih.hamedgeek.top

**Comment by S0R0SH** [comment]
سلام. فقط خواستم تشکر کنم از زحمات همه دوستان. همچنین یکی از فیلتر چی های محترم رو معرفی کنم که بشناسید و به هیچ عنوان بهش آدرس ندید حتی اگر با پول زیاد بخواد کانفیگ بخره. روش کارش اینکه میاد از شما کانفیگ میگیره یکباره مثلا 3 ماهه خرید میکنه بعد که کانفیگ رو از شما دریافت کرد به سرعت میزنه زیرش و بهونه میاره که وصل نمیشم و پولش رو میخاد. دقیقه چندساعت بعد سرورتون فیتلر میشه. 😒
مشخصات : akbarinabi@yahoo.com
اسم : نبی اکبری
تلفن : 989376212726
حالا بگید شاید همزمان بوده اما نه برای 2 ادمین و 2 سرور مختلف.
بازم ممنونم از آقا وحید  🙏

**Comment by vfarid** [comment]
@HamedSanaei متشکرم از همکاری شما
