### ISSUE TITLE
Question دامین فیلتر شده

### ISSUE THREAD

**Issue by saeex71** [vfarid/cf-clean-ips#11]
اگه دامینم فیلتر شده باشه بازم ای پی تمیز که روش هست به درد میخوره؟
من میتونم بصورت روزانه مخایرات ایرانسل رایتل و مبین نت اسکن کنم

**Comment by vfarid** [comment]
بله چون روی گیت هاب داره resolve میشه، فرقی نمیکنه فیلتر باشه یا نباشه
