### ISSUE TITLE
رنج آی پی بر اساس کشور

### ISSUE THREAD

**Issue by Call4Internet** [vfarid/cf-clean-ips#19]
اگه آی پی ها رو بر اساس نام کشورها مشخص کنید خیلی  راحت تر میشه اونها رو بر اساس موقعیت مکانی و مسافت انتخاب کرد

**Comment by vfarid** [comment]
رنج آی‌پی های کلادفلر تعلق به مکان یا کشور مشخصی ندارن و بر اساس الگوریتم کلادفلر به نزدیکترین دیتاسنتر وصل میشن.
