### ISSUE TITLE
Clean IP

### ISSUE THREAD

**Issue by adihnr** [vfarid/cf-clean-ips#2]
shtcn.adihnrr.eu.org
mcicn.adihnrr.eu.org

**Comment by AmirhosseinAshouri** [comment]
irancell.fastynet.cloud

**Comment by Eric01001101** [comment]
mtn.chamburak520.online
irancell.chamburak520.online

**Comment by xJuniorProgrammer** [comment]
mci.vcdn.online
sht.vcdn.online
mtn.vcdn.online

**Comment by vfarid** [comment]
متشکرم از همگی. تمام سابدامین ها رو اضافه کردم. لطفا حتما روزانه آپدیت کنید. کد اسکنر رو به زودی آپدیت می‌کنم تا امکان بررسی مجدد آی‌پی های تمیزتون هم فراهم بشه.

**Comment by Eric01001101** [comment]
> mtn.chamburak520.online
> irancell.chamburak520.online

آقا ساب دامین های قبلی گویا یکیش ایراد داشت. عوضش کردم.

mtn.chamburak520.online
mci.chamburak520.online
