### ISSUE TITLE
همراه اول

### ISSUE THREAD

**Issue by hamidbaran** [vfarid/cf-clean-ips#3]
برای همراه اول
mci.ma7ta.online

**Comment by hamidbaran** [comment]
mtn.ma7ta.online 
برای ایرانسل
sht.ma7ta.online هم برای شاتل

**Comment by vfarid** [comment]
متشکرم. تمام سابدامین ها رو اضافه کردم. لطفا حتما روزانه آپدیت کنید. کد اسکنر رو به زودی آپدیت می‌کنم تا امکان بررسی مجدد آی‌پی های تمیزتون هم فراهم بشه.
