### ISSUE TITLE
Check IPs before adding to list

### ISSUE THREAD

**Issue by aleskxyz** [vfarid/cf-clean-ips#5]
I think we should check IPs before adding them to list.
It seems some of lists are not updated and their IPs are actually dead!
For example this list is not working for me:
`104.23.0.214
162.158.110.149
104.22.176.153
172.64.36.88
104.30.3.192
104.30.191.43
104.31.209.227
172.70.251.118
172.65.174.82
162.158.106.79
172.64.248.243
104.26.105.60
104.30.245.211
172.64.213.83
104.29.89.97
104.22.191.236
104.29.94.121
172.71.22.141
104.31.83.180
141.11.194.136`

I should say that I have my own server behind CF so I'm not using workers.
Maybe this list is ok with workers, but it is not working with my domain at least.

**Comment by aleskxyz** [comment]
> I think we should check IPs before adding them to list. It seems some of lists are not updated and their IPs are actually dead! For example this list is not working for me: `104.23.0.214 162.158.110.149 104.22.176.153 172.64.36.88 104.30.3.192 104.30.191.43 104.31.209.227 172.70.251.118 172.65.174.82 162.158.106.79 172.64.248.243 104.26.105.60 104.30.245.211 172.64.213.83 104.29.89.97 104.22.191.236 104.29.94.121 172.71.22.141 104.31.83.180 141.11.194.136`
> 
> I should say that I have my own server behind CF so I'm not using workers. Maybe this list is ok with workers, but it is not working with my domain at least.

I can confirm that these servers are not responding at all! You cannot connect to their 443 port even by telnet.
It is better to implement a test function to see that these servers are up or not. if not remove it from list.

**Comment by vfarid** [comment]
Its impossible to test provided IPs on github. IP addresses should be checked/rechecked over its operator's internet.
By the way, i updated the repo to keep creation date of each ip and sort IPs by date.
