### ISSUE TITLE
جمع آوری آی پی اینترانت!

### ISSUE THREAD

**Issue by taregh-n** [vfarid/cf-clean-ips#7]
سلام و تشکر از کدها و پروؤه های عالیتون
یه ایرادی وجود داره مث اینکه، آی پی های سانسوچی رو هم داره جمع میکنه!
  - 10.10.34.36        MCI      adihnrr.eu.org    1681158090

![ip 10.10.34.36](https://i.ibb.co/dLPC5VQ/Screenshot-2023-04-10-235537.png)

**Comment by mostafa5804** [comment]
سلام
اینipکجاست؟ دقیقا الان همینipپنل شده کلهم از کار افتاد😅
و اینکه راهکار چیه؟

**Comment by rezasadighpour** [comment]
تمایل به مشارکت دارم 😊

**Comment by vfarid** [comment]
اگه پرووایدرها آی پی اشتباه بزنن به لیست اضافه میشه. تنها روش اصلاح اینه که ببینیم کدوم پرووایدر آی پی اشتباه تزریق میکنه و حذفش کنم. الان دیدم این مشکل رفع شده از سمت پرووایدر مربوطه

**Comment by vfarid** [comment]
@rezasadighpour اگه دامین آی‌پی تمیز دارید همینجا بفرستید تا به پروژه اضافه بشه

**Comment by rezasadighpour** [comment]
> @rezasadighpour اگه دامین آی‌پی تمیز دارید همینجا بفرستید تا به پروژه اضافه بشه

دارم ولی دامنه اصلی نمیشه  با دامنه ای که می‌خوام به شما بدم CNAME بزنم میشه؟؟
